import moviesPhoto from '../images/pic.png';

const test = [
  {
    movieId: 1,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 2,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 3,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 4,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 5,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 6,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 7,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 8,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
  {
    id: 9,
    nameRU: '33 слова о дизайне',
    nameEN: '33',
    director: 'Стивен',
    country: 'РФ',
    year: '2016',
    duration: 60,
    description:
      'Описание',
    trailerLink: 'https://www.youtube.com/watch?v=3WaA4oH-5R4&t=2s',
    image: moviesPhoto,
    thumbnail: moviesPhoto,
  },
];

export default test;
